import numpy as np
import scipy
import torch
import pickle
import json
import os 

from reservoirgrid.models import Reservoir
from reservoirgrid.helpers import utils, viz, reservoir_tests, chaos_utils

path = "research\\Input_Discretization\\results\\Chaotic\\"
system_name = "RosslerLHS"
PP = 90
system_path = path + system_name

if not os.path.exists("research/Input_Discretization/Plots/3DPlots/" + system_name):
    os.makedirs("research/Input_Discretization/Plots/3DPlots/"+ system_name)

file_path = system_path + "/" + str(PP) + ".0.pkl"

with open(file_path, "rb") as f:
    results = pickle.load(f)

# ==============================================================================
# ALIGNMENT LAYER: Sorts results to match Heatmap Indexing
# ==============================================================================
# Path to the legend generated by your heatmap script (using RMSE as a reliable reference)
legend_path = "research/Input_Discretization/Plots/HeatMaps/" + system_name + "/metadata/jsdivergence_param_legend.json"

if os.path.exists(legend_path):
    print(f"Found heatmap metadata legend at {legend_path}. Aligning indices...")
    with open(legend_path, "r") as f:
        legend_data = json.load(f)
    
    # Map from hashable parameter tuple -> heatmap column index
    param_to_heatmap_idx = {}
    for entry in legend_data:
        combo_dict = entry["param_combo"]
        combo_tuple = tuple(sorted(combo_dict.items()))
        param_to_heatmap_idx[combo_tuple] = entry["col_idx"]
    
    # Sort the raw results list based on the heatmap column index mapping
    # Fallback to infinity if a parameter combination isn't found in the legend
    results = sorted(
        results, 
        key=lambda r: param_to_heatmap_idx.get(tuple(sorted(r["parameters"].items())), float('inf'))
    )
else:
    print("WARNING: Heatmap legend JSON not found! Indices will remain misaligned.")
    print("Run heatmap generation script first to generate the metadata.")
# ==============================================================================

metrics_dict = {
    "KL Divergence": [chaos_utils.kl_divergence(r["true_value"], r["predictions"]) for r in results],
    "JS Divergence": [chaos_utils.js_divergence(r["true_value"], r["predictions"]) for r in results],
    "RMSE": [utils.RMSE(r["true_value"], r["predictions"]) for r in results],
    "Symmetric KL": [chaos_utils.symmetric_kl(r["true_value"], r["predictions"]) for r in results],
    "PSD Error": [chaos_utils.psd_error(r["true_value"], r["predictions"])[0] for r in results]
}

viz.plot_multidimensional_3d(
    results, 
    system_name=system_name, 
    pp = PP, 
    metrics_dict = metrics_dict, 
    save_html=True, 
    path="research/Input_Discretization/Plots/3DPlots/"
)
